version: '3.8'

services:
  # Redis для кеширования товаров
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Сервис платежей
  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - redis

  # Основное веб-приложение
  intershop-main:
    build:
      context: .
      dockerfile: intershop-main/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_REDIS_HOST=redis
      - PAYMENT_SERVICE_URL=http://payment-service:8081
    depends_on:
      - redis
      - payment-service
