server:
  port: 8080
  servlet:
    context-path: /intershop

image:
  folder: static/images

spring:
  application:
    name: intershop
    
  # R2DBC конфигурация для H2
  r2dbc:
    url: r2dbc:h2:mem:///postdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: qwerty
    pool:
      enabled: true
      initial-size: 10
      max-size: 20

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.h2: DEBUG
