server:
  servlet:
    context-path: /intershop

image:
  folder: static/images

spring:
  application:
    name: intershop
  datasource:
    url: jdbc:h2:mem:postdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: qwerty
  jpa:
    hibernate:
      ddl-auto: validate

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.jdbc: DEBUG
