server:
  port: 8080

image:
  folder: static/images

spring:
  application:
    name: intershop
    
  # R2DBC конфигурация для H2
  r2dbc:
    url: r2dbc:h2:mem:///postdb
    username: sa
    password: qwerty
    pool:
      enabled: true
      initial-size: 10
      max-size: 20

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  # Redis конфигурация (как в уроке)
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:127.0.0.1}
      port: 6379
  cache:
    redis:
      time-to-live: PT3M

  # Thymeleaf автоконфигурация
  thymeleaf:
    encoding: UTF-8
    cache: false

  webflux:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
    
  # HTTP кодировка
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.h2: DEBUG
    org.springframework.data.redis: DEBUG
    io.lettuce.core: INFO
